linters:

    BangFormat:
        enabled: true
        space_before_bang: true
        space_after_bang: false

    BorderZero:
        enabled: true

    ColorKeyword:
        enabled: true

    Comment:
        enabled: false

    DebugStatement:
        enabled: true

    DeclarationOrder:
        enabled: true

    DuplicateProperty:
        enabled: false

    ElsePlacement:
        enabled: true
        style: same_line

    EmptyLineBetweenBlocks:
        enabled: true
        ignore_single_line_blocks: false

    EmptyRule:
        enabled: true

    FinalNewline:
        enabled: false
        present: false

    HexLength:
        enabled: true
        style: short

    HexNotation:
        enabled: true
        style: uppercase

    HexValidation:
        enabled: true

    IdSelector:
        enabled: false

    ImportPath:
        enabled: true
        leading_underscore: false
        filename_extension: false

    ImportantRule:
        enabled: false

    Indentation:
        enabled: true
        character: tab
        width: 1

    LeadingZero:
        enabled: true
        style: include_zero

    MergeableSelector:
        enabled: false
        force_nesting: false

    NameFormat:
        enabled: true
        convention: hyphenated_lowercase
        allow_leading_underscore: true

    NestingDepth:
        enabled: true
        max_depth: 5

    PlaceholderInExtend:
        enabled: false

    PropertySortOrder:
        enabled: false
        ignore_unspecified: false

    PropertySpelling:
        enabled: true
        extra_properties: []

    QualifyingElement:
        enabled: true
        allow_element_with_attribute: true
        allow_element_with_class: false
        allow_element_with_id: false

    SelectorDepth:
        enabled: true
        max_depth: 5

    SelectorFormat:
        enabled: true
        convention: hyphenated_lowercase

    Shorthand:
        enabled: true

    SingleLinePerProperty:
        enabled: true
        allow_single_line_rule_sets: false

    SingleLinePerSelector:
        enabled: true

    SpaceAfterComma:
        enabled: true

    SpaceAfterPropertyColon:
        enabled: true
        style: one_space

    SpaceAfterPropertyName:
         enabled: true

    SpaceBeforeBrace:
        enabled: true
        style: space
        allow_single_line_padding: true

    SpaceBetweenParens:
        enabled: true
        spaces: 0

    StringQuotes:
        enabled: true
        style: double_quotes

    TrailingSemicolon:
        enabled: true

    TrailingZero:
        enabled: true

    UnnecessaryMantissa:
        enabled: true

    UnnecessaryParentReference:
        enabled: true

    UrlFormat:
        enabled: false

    UrlQuotes:
        enabled: true

    VendorPrefix:
        enabled: false

    ZeroUnit:
        enabled: true
        severity: warning
